# Generated by Django 4.2.7 on 2023-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_app', '0003_alter_person_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='address2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
