# Generated by Django 4.2.7 on 2023-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSV_app', '0004_alter_person_address1_alter_person_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='pincode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=255),
        ),
    ]
